Implementation
mrojasabregu/product-service pull request #2
Opened 2021-11-17 21:26 UTC by belenyammal

2021-11-18 14:36 UTC, maalbera commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
No subir estos archivos

2021-11-18 14:36 UTC, maalbera commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
No subir

2021-11-18 14:36 UTC, maalbera commented on .mvn/wrapper/MavenWrapperDownloader.java
> +public class MavenWrapperDownloader {
No subir .mvm

2021-11-18 14:36 UTC, maalbera commented on .mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.8.3/apache-maven-3.8.3-bin.zip
no subir

2021-11-18 14:36 UTC, maalbera commented on mvnw
> +# ----------------------------------------------------------------------------
no subir

2021-11-18 14:36 UTC, maalbera commented on src/main/java/com/marketplace/product/service/impl/ImplProductService.java
> +public class ImplProductService implements ProductService {
cambiar a ProductServiceImpl

2021-11-24 19:57 UTC, mrojasabregu requested changes

2021-11-24 19:57 UTC, mrojasabregu commented on .idea/.gitignore
> +/shelf/
el .idea no va

2021-11-24 19:57 UTC, mrojasabregu commented on pom.xml
> +<<<<<<< HEAD
error de merge

2021-11-24 19:57 UTC, mrojasabregu commented on src/main/java/com/marketplace/product/controller/request/ProductRequest.java
> +    Float price;
usar BigDecimal

2021-11-24 19:57 UTC, mrojasabregu commented on src/main/java/com/marketplace/product/domain/mapper/ProductMapper.java
> +                .KEYWORD(productRequest.getKeywords())
por que esta en mayuscula?

2021-11-24 19:57 UTC, mrojasabregu commented on src/main/java/com/marketplace/product/domain/model/Keyword.java
> +    @EmbeddedId
usar
````
   @Id
    @GeneratedValue(generator = "uuid2")
    @GenericGenerator(name = "uuid2", strategy = "org.hibernate.id.UUIDGenerator")
```

2021-11-24 19:57 UTC, mrojasabregu commented on src/main/java/com/marketplace/product/domain/model/Product.java
> +    List<Keyword> KEYWORD=new ArrayList<>();
tiene que ser en minuscula

2021-11-24 19:57 UTC, mrojasabregu commented on src/main/java/com/marketplace/product/service/impl/ImplProductService.java
> +        if (request.getProductId() != null){
aca esta mal porque en el request vos no vas a tener el productId

2021-11-24 19:57 UTC, mrojasabregu commented on src/main/java/com/marketplace/product/service/impl/ImplProductService.java
> +        if (request.getProductId() != null){
tendrias que validar o buscar el producto por sku

2021-11-24 19:57 UTC, mrojasabregu commented on docker-compose.yml
> +      - "8088:8080"
ponelo en 80, asi lo levantamos dierectamnete en gcp

2021-11-24 19:57 UTC, mrojasabregu commented on mvnw.cmd
> +@REM distributed with this work for additional information
no va este archivo

2021-11-24 19:57 UTC, mrojasabregu commented on pom.xml
> +	<version>0.0.1-SNAPSHOT</version>
pone la version 1.0.0

2021-11-24 19:57 UTC, mrojasabregu commented on src/main/java/com/marketplace/product/controller/request/CancelReserveProductRequest.java
> +    //@NotBlank(message = "El campo sku no puede ser null o vacio.")
debe ser not null

2021-11-24 20:16 UTC, mrojasabregu approved these changes

2021-11-24 20:16 UTC, merged